### ISSUE TITLE
Clicking an on-cooldown item and then clicking and consuming a different item afterwards doesn't display cooldowns

### ISSUE THREAD

**Issue by Grantapher** [CopyPastaOSRS/consumable-cooldowns#2]
To reproduce:
1. Consume an item.
1. Try consuming a different item while on cooldown.
    * It won't do anything because it is on cooldown.
1. Try consuming a third different item once cooldown ends
1. The cooldown indicators won't show.

Note: if you click on the same item for step 3 as you did in step 2, it will work correctly.

Gif: first set of items is reproducing the issue, second set is showing that it works correctly if it is the same item.
![bug](https://github.com/CopyPastaOSRS/consumable-cooldowns/assets/6396799/79f12dab-c241-4d19-b4e7-aa46b940e37b)

**Comment by CopyPastaOSRS** [comment]
Thanks for reporting. I've been able to reproduce this and fix the issue locally. I'm also working on fixing & testing another bug so will update the plugin once I'm certain that is also fixed. Should hopefully be tomorrow.

**Comment by CopyPastaOSRS** [comment]
Fixed with https://github.com/runelite/plugin-hub/pull/4454
