### ISSUE TITLE
Suggestion: RS3/WoW like timer for cooldown

### ISSUE THREAD

**Issue by ritwikvd** [CopyPastaOSRS/consumable-cooldowns#3]
Instead of a number ticking down, can we have a cooldown like the ones used on rs3 and wow where the item is greyed out and there's a rotating dial which completes a round when the item is off cd.

**Comment by CopyPastaOSRS** [comment]
Added with https://github.com/CopyPastaOSRS/consumable-cooldowns/pull/8 (version 1.1.0). Will be released once RuneLite approves the update.
