### ISSUE TITLE
You can drink absorption potions once per tick. The plugin currently thinks they have a 2-tick cooldown. 

### ISSUE THREAD

**Issue by NoahTingey** [CopyPastaOSRS/consumable-cooldowns#5]

**Comment by CopyPastaOSRS** [comment]
Fixed with the release of version 1.0.2. It might be that you need to restart your client for the plugin to be updated.

The version is visible in the plugin hub list of the client.
![image](https://github.com/CopyPastaOSRS/consumable-cooldowns/assets/66518222/9cbaaa05-4465-42ef-b62e-d42d64463658)
