### ISSUE TITLE
Cooldown not work while in bank

### ISSUE THREAD

**Issue by clementchen163** [CopyPastaOSRS/consumable-cooldowns#7]
could you add the cooldown overlay so it works while you are in the bank? it is helpful when trying to prepot before a raid

**Comment by CopyPastaOSRS** [comment]
I definitely want to add this as it was bugging me too while prepotting. Will try and get this in the next update (no promises though :P)

**Comment by CopyPastaOSRS** [comment]
Should be fixed with https://github.com/CopyPastaOSRS/consumable-cooldowns/pull/8 (version 1.1.0). Will be released once RuneLite approves the update.

**Comment by clementchen163** [comment]
thanks!
